destination: &ci_cd_ns demo-ci-cd

##############
# Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - Validate=true

##############
# Argo App of Apps declaration
#############

# Custom values override the default values in Helm Charts
applications:
  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_path: ""
    source_ref: "0.0.5"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    ignore_differences:
      - group: route.openshift.io
        kind: Route
        jsonPointers:
          - /status/ingress
  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-0.0.21"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    values:
      persistence: false
      source_secrets:
        - name: git-auth
          username: idm-sa
          password: thisisdefinitelynotmypassword🦆🦆🦆
        - name: nexus-password
          username: admin
          password: admin123
        - name: argocd-token
          username: token
          password: aaa.bbb.ccc
      imagestreams:
        - name: jenkins-agent-mvn
        - name: jenkins-agent-npm
    ignore_differences:
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
          - /spec/template/spec/containers/0/image
          - /spec/triggers/0/imageChangeParams/lastTriggeredImage
      - group: build.openshift.io
        kind: BuildConfig
        jsonPointers:
          - /spec/triggers
  # Sonarqube
  - name: sonarqube
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/sonarqube
    source_ref: "sonarqube-0.0.9"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    values:
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/8.35/checkstyle-sonar-plugin-8.38.jar
          - https://repo1.maven.org/maven2/org/sonarsource/java/sonar-java-plugin/6.9.0.23563/sonar-java-plugin-6.9.0.23563.jar
          - https://repo1.maven.org/maven2/org/sonarsource/jacoco/sonar-jacoco-plugin/1.1.0.898/sonar-jacoco-plugin-1.1.0.898.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.7/sonar-dependency-check-plugin-2.0.7.jar
          - https://github.com/SonarSource/SonarJS/releases/download/6.2.2.13315/sonar-javascript-plugin-6.2.2.13315.jar
          - https://github.com/SonarSource/SonarTS/releases/download/2.1.0.4359/sonar-typescript-plugin-2.1.0.4362.jar