kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-operator-helm
  namespace: sealed-secrets
subjects:
- kind: ServiceAccount
  name: sealed-secrets-operator-helm
  namespace: sealed-secrets
roleRef:
  kind: ClusterRole
  name: sealed-secrets-operator-helm
  apiGroup: rbac.authorization.k8s.io
